# Максимум соединений и каналов
channel_max = 256
connection_max = 128

# Настройки производительности
vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 2GB

# TCP настройки
tcp_listen_options.backlog = 4096
tcp_listen_options.nodelay = true
tcp_listen_options.sndbuf = 32768
tcp_listen_options.recbuf = 32768

# Heartbeat
heartbeat = 60

# Limits для queue
queue_master_locator = min-masters